fix(website): correct syntax error in ScalaDoc generation command in GitHub Actions workflow

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -58,7 +58,7 @@ jobs:
         run: git submodule update --remote --merge
 
       - name: Generate ScalaDoc
-        run: sbt doc& & echo "ScalaDoc generation successful" || (echo "ScalaDoc generation failed" && exit 1)
+        run: sbt doc && echo "ScalaDoc generation successful" || (echo "ScalaDoc generation failed" && exit 1)
 
       - name: Move ScalaDoc to docs/public/scaladoc
         run: |
