chore: enhance GitHub workflows for ScalaDoc and Scoverage report generation
- Updated gh-pages.yml to include success messages for ScalaDoc and Scoverage report generation, improving feedback during the CI process.
- Modified BuildAndTest.yml to correct the concurrency group naming for pull requests, ensuring accurate job management.

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -58,7 +58,7 @@ jobs:
         run: git submodule update --remote --merge
 
       - name: Generate ScalaDoc
-        run: sbt doc
+        run: sbt doc& & echo "ScalaDoc generation successful" || (echo "ScalaDoc generation failed" && exit 1)
 
       - name: Move ScalaDoc to docs/public/scaladoc
         run: |
@@ -69,7 +69,7 @@ jobs:
         run: |
           sbt 'set coverageEnabled := true'
           sbt clean coverage test
-          sbt coverageReport
+          sbt coverageReport && echo "Scoverage report generation successful" || (echo "Scoverage report generation failed" && exit 1)
 
       - name: Move Scoverage Report to docs/public/coverage
         run: |
